//! sett design tokens. Generated by `pnpm build` in `packages/tokens`; run it before `cargo build`.
#![forbid(unsafe_code)]
#![no_std]

include!("../dist/tokens.rs");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn colours_are_unit_srgb() {
        for c in [light::COLOR_SEL, dark::COLOR_SEL, light::SESSION_YK_MAIN, light::MAP_SURFACE_DRIVING] {
            assert!(c.iter().all(|x| (0.0..=1.0).contains(x)));
        }
    }

    #[test]
    fn dark_differs_from_light() {
        assert_ne!(light::COLOR_BG, dark::COLOR_BG);
    }

    #[test]
    fn dimensions_and_motion() {
        assert_eq!(RADIUS_CHIP, 4.0);
        assert_eq!(STROKE_LIT, 1.6);
        assert_eq!(MOTION_ITEM_PULSE_MS, 700.0);
        assert_eq!(MOTION_FRAME_ROTATE_MS, 6000.0);
        assert_eq!(FONT_MAP_LABEL, 10.0);
        assert_eq!(SESSION_ORDER[0], "yk");
    }
}
