// sett tokens build. Source of truth: src/*.json (DTCG 2025.10).
// Style Dictionary parses and resolves the sets; this file composes the targets:
//   dist/sett.css     :root light, dark under prefers-color-scheme and [data-theme="dark"]
//   dist/tokens.ts    base / light / dark as typed objects with css-ready values
//   dist/tokens.json  flat list per set, for docs pages
//   dist/tokens.rs    pub const per token; colours [f32; 3], dimensions f32, strokes as dash arrays (empty = solid)
//   dist/sett-theme.{light,dark}.json  Theia / VS Code colour theme, see theme.mjs
import StyleDictionary from 'style-dictionary';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderTheme } from './theme.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const src = (f) => join(here, 'src', f);
const dist = join(here, 'dist');
const PREFIX = 'sett';
const HEADER = 'generated by @tau-rs/sett-tokens from src/*.json. Edit the JSON, not this file.';

// ---------- load ----------
async function loadSet(file) {
  const sd = new StyleDictionary({ source: [src(file)], platforms: { raw: { transforms: [] } }, log: { verbosity: 'silent' } });
  await sd.hasInitialized;
  const tree = await sd.exportPlatform('raw');
  const out = [];
  (function walk(node, path) {
    if (node && typeof node === 'object' && '$value' in node) {
      out.push({ path, type: node.$type, value: node.$value, description: node.$description ?? '' });
      return;
    }
    for (const [k, v] of Object.entries(node)) if (!k.startsWith('$') && v && typeof v === 'object') walk(v, [...path, k]);
  })(tree, []);
  return out;
}

// ---------- naming ----------
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const cssName = (path) => `--${PREFIX}-${path.map(kebab).join('-')}`;
const rustName = (path) => path.map(kebab).join('-').replace(/-/g, '_').toUpperCase();

// ---------- value renderers ----------
const unsupported = [];
function hexWithAlpha(c) {
  if (c.alpha === undefined || c.alpha === 1) return c.hex.toUpperCase();
  const [r, g, b] = c.components.map((x) => Math.round(x * 255));
  return `rgba(${r}, ${g}, ${b}, ${c.alpha})`;
}
const shadowCss = (v) => `${v.offsetX.value}${v.offsetX.unit} ${v.offsetY.value}${v.offsetY.unit} ${v.blur.value}${v.blur.unit} ${v.spread.value}${v.spread.unit} ${hexWithAlpha(v.color)}`;
function toCss(t) {
  const v = t.value;
  switch (t.type) {
    case 'color': return hexWithAlpha(v);
    case 'dimension':
    case 'duration': return `${v.value}${v.unit}`;
    case 'fontFamily': return v.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
    case 'fontWeight':
    case 'number': return String(v);
    case 'cubicBezier': return `cubic-bezier(${v.join(', ')})`;
    case 'string': return JSON.stringify(v);
    case 'shadow': return (Array.isArray(v) ? v : [v]).map(shadowCss).join(', ');
    case 'strokeStyle': return typeof v === 'string' ? v : v.dashArray.map((d) => `${d.value}`).join(' ');
    default: unsupported.push(`${t.path.join('.')} (${t.type}) has no css rendering`); return null;
  }
}
// ts: numbers stay numbers, glyph strings stay raw text, everything else is the css-ready string
const toTs = (t) => (t.type === 'number' || t.type === 'fontWeight' || t.type === 'string' ? t.value : toCss(t));

const f32 = (n) => (Number.isInteger(n) ? `${n}.0` : String(n));
function toRust(t) {
  const v = t.value;
  const name = rustName(t.path);
  switch (t.type) {
    case 'color':
      return `pub const ${name}: [f32; 3] = [${v.components.map(f32).join(', ')}];`;
    case 'dimension':
      if (v.unit !== 'px') { unsupported.push(`${t.path.join('.')}: unit ${v.unit} not expressed in rust`); return null; }
      return `pub const ${name}: f32 = ${f32(v.value)};`;
    case 'duration': {
      const ms = v.unit === 's' ? v.value * 1000 : v.value;
      return `pub const ${name}_MS: f32 = ${f32(ms)};`;
    }
    case 'fontFamily': return `pub const ${name}: &[&str] = &[${v.map((s) => JSON.stringify(s)).join(', ')}];`;
    case 'fontWeight': return `pub const ${name}: u16 = ${v};`;
    case 'number': return `pub const ${name}: f32 = ${f32(v)};`;
    case 'cubicBezier': return `pub const ${name}: [f32; 4] = [${v.map(f32).join(', ')}];`;
    case 'string': return `pub const ${name}: &str = ${JSON.stringify(v)};`;
    case 'shadow': {
      const one = (sv) => `Shadow { color: [${sv.color.components.map(f32).join(', ')}], alpha: ${f32(sv.color.alpha ?? 1)}, offset: [${f32(sv.offsetX.value)}, ${f32(sv.offsetY.value)}], blur: ${f32(sv.blur.value)}, spread: ${f32(sv.spread.value)} }`;
      return Array.isArray(v) ? `pub const ${name}: &[Shadow] = &[${v.map(one).join(', ')}];` : `pub const ${name}: Shadow = ${one(v)};`;
    }
    case 'strokeStyle':
      return `pub const ${name}: &[f32] = &[${typeof v === 'string' ? '' : v.dashArray.map((d) => f32(d.value)).join(', ')}];`;
    default: unsupported.push(`${t.path.join('.')} (${t.type}) has no rust rendering`); return null;
  }
}

// ---------- targets ----------
const declBlock = (tokens, indent = '  ') => tokens.map((t) => `${indent}${cssName(t.path)}: ${toCss(t)};`).join('\n');
function css({ base, light, dark }) {
  return [
    `/* ${HEADER} */`,
    `:root {`, declBlock(base), declBlock(light), `}`,
    `@media (prefers-color-scheme: dark) {`, `  :root {`, declBlock(dark, '    '), `  }`, `}`,
    `[data-theme="dark"] {`, declBlock(dark), `}`,
    `[data-theme="light"] {`, declBlock(light), `}`,
    '',
  ].join('\n');
}

function nest(tokens, render) {
  const root = {};
  for (const t of tokens) {
    let n = root;
    for (const k of t.path.slice(0, -1)) n = n[k] ??= {};
    n[t.path.at(-1)] = render(t);
  }
  return root;
}
function ts(sets) {
  const j = (o) => JSON.stringify(o, null, 2);
  return [
    `// ${HEADER}`,
    `export const base = ${j(nest(sets.base, toTs))} as const;`,
    `export const light = ${j(nest(sets.light, toTs))} as const;`,
    `export const dark = ${j(nest(sets.dark, toTs))} as const;`,
    `export const themes = { light, dark } as const;`,
    `export type Theme = keyof typeof themes;`,
    `/** session colours, in assignment order */`,
    `export const sessionOrder = ${j(Object.keys(nest(sets.light, toTs).session))} as const;`,
    `export type SessionId = (typeof sessionOrder)[number];`,
    `/** css custom property for a token path, e.g. cssVar('color', 'sel') → var(--sett-color-sel) */`,
    `export const cssVar = (...path: string[]): string => \`var(--${PREFIX}-\${path.map((s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()).join('-')})\`;`,
    '',
  ].join('\n');
}
function json(sets) {
  const flat = (tokens, set) => tokens.map((t) => ({ set, name: cssName(t.path), path: t.path, type: t.type, css: toCss(t), value: t.value, description: t.description }));
  return JSON.stringify({ base: flat(sets.base, 'base'), light: flat(sets.light, 'light'), dark: flat(sets.dark, 'dark') }, null, 2) + '\n';
}
function rust(sets) {
  const lines = (tokens, indent) => tokens.map(toRust).filter(Boolean).map((l) => indent + l).join('\n');
  return [
    `// ${HEADER}`,
    `#[derive(Debug, Clone, Copy, PartialEq)]`,
    `pub struct Shadow { pub color: [f32; 3], pub alpha: f32, pub offset: [f32; 2], pub blur: f32, pub spread: f32 }`,
    `/// session colours, in assignment order`,
    `pub const SESSION_ORDER: [&str; ${Object.keys(nest(sets.light, toTs).session).length}] = [${Object.keys(nest(sets.light, toTs).session).map((s) => JSON.stringify(s)).join(', ')}];`,
    lines(sets.base, ''),
    `pub mod light {`, `    use super::Shadow;`, lines(sets.light, '    '), `}`,
    `pub mod dark {`, `    use super::Shadow;`, lines(sets.dark, '    '), `}`,
    '',
  ].join('\n');
}

// ---------- run ----------
const sets = { base: await loadSet('base.json'), light: await loadSet('light.json'), dark: await loadSet('dark.json') };
const lp = sets.light.map((t) => t.path.join('.')), dp = sets.dark.map((t) => t.path.join('.'));
if (lp.join('\n') !== dp.join('\n')) throw new Error('light.json and dark.json must define the same token paths');
await mkdir(dist, { recursive: true });
await writeFile(join(dist, 'sett.css'), css(sets));
await writeFile(join(dist, 'tokens.ts'), ts(sets));
await writeFile(join(dist, 'tokens.json'), json(sets));
await writeFile(join(dist, 'tokens.rs'), rust(sets));
for (const type of ['light', 'dark'])
  await writeFile(join(dist, `sett-theme.${type}.json`), JSON.stringify(renderTheme(sets[type], { name: `sett ${type}`, type }), null, 2) + '\n');
const report = { base: sets.base.length, light: sets.light.length, dark: sets.dark.length, unsupported: [...new Set(unsupported)] };
await writeFile(join(dist, 'report.json'), JSON.stringify(report, null, 2) + '\n');
console.log(`sett-tokens: base ${report.base} · light ${report.light} · dark ${report.dark}${report.unsupported.length ? `\n  not expressed: ${report.unsupported.join('; ')}` : ''}`);
